/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartUploadRouteImport } from './routes/smart-upload'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ApiUploadPdfRouteImport } from './routes/api/upload-pdf'
import { Route as ApiProcessPrintRouteImport } from './routes/api/process-print'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'

const SmartUploadRoute = SmartUploadRouteImport.update({
  id: '/smart-upload',
  path: '/smart-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPdfRoute = ApiUploadPdfRouteImport.update({
  id: '/api/upload-pdf',
  path: '/api/upload-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessPrintRoute = ApiProcessPrintRouteImport.update({
  id: '/api/process-print',
  path: '/api/process-print',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/smart-upload': typeof SmartUploadRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/process-print': typeof ApiProcessPrintRoute
  '/api/upload-pdf': typeof ApiUploadPdfRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/smart-upload': typeof SmartUploadRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/process-print': typeof ApiProcessPrintRoute
  '/api/upload-pdf': typeof ApiUploadPdfRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/smart-upload': typeof SmartUploadRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/process-print': typeof ApiProcessPrintRoute
  '/api/upload-pdf': typeof ApiUploadPdfRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/login'
    | '/register'
    | '/smart-upload'
    | '/account/orders'
    | '/admin/login'
    | '/api/process-print'
    | '/api/upload-pdf'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/login'
    | '/register'
    | '/smart-upload'
    | '/account/orders'
    | '/admin/login'
    | '/api/process-print'
    | '/api/upload-pdf'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/login'
    | '/register'
    | '/smart-upload'
    | '/account/orders'
    | '/admin/login'
    | '/api/process-print'
    | '/api/upload-pdf'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SmartUploadRoute: typeof SmartUploadRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiProcessPrintRoute: typeof ApiProcessPrintRoute
  ApiUploadPdfRoute: typeof ApiUploadPdfRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-upload': {
      id: '/smart-upload'
      path: '/smart-upload'
      fullPath: '/smart-upload'
      preLoaderRoute: typeof SmartUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-pdf': {
      id: '/api/upload-pdf'
      path: '/api/upload-pdf'
      fullPath: '/api/upload-pdf'
      preLoaderRoute: typeof ApiUploadPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-print': {
      id: '/api/process-print'
      path: '/api/process-print'
      fullPath: '/api/process-print'
      preLoaderRoute: typeof ApiProcessPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SmartUploadRoute: SmartUploadRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiProcessPrintRoute: ApiProcessPrintRoute,
  ApiUploadPdfRoute: ApiUploadPdfRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
